# COMP-07 Constants（定数一覧）
# 対応要件: NFR-05, CON-02
# 他の全モジュールはここで定義される定数を参照し、値をハードコーディングしない。

BOARD_SIZE = 15
WIN_LENGTH = 5

EMPTY = "EMPTY"
BLACK = "BLACK"
WHITE = "WHITE"

# 関数設計書3章の型定義に対応する型エイリアス（実行時の値はstr）
Color = str  # BLACK または WHITE
StoneValue = str  # EMPTY / BLACK / WHITE のいずれか

CELL_SIZE = 32
MARGIN = 32

WINDOW_WIDTH = CELL_SIZE * (BOARD_SIZE - 1) + MARGIN * 2
WINDOW_HEIGHT = WINDOW_WIDTH + 60

STONE_COLORS = {
    BLACK: "black",
    WHITE: "white",
}

HIGHLIGHT_COLOR = "red"

BOARD_BG_COLOR = "#DEB887"
STONE_OUTLINE_COLOR = "black"
STONE_RADIUS_MARGIN = 2
HIGHLIGHT_RADIUS_MARGIN = 6
HIGHLIGHT_LINE_WIDTH = 3

STATUS_FONT_SIZE = 14
STATUS_LABEL_PADY = 8
RESET_BUTTON_PADY = 4
